### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Szo-gun** [jilleb/odis2vcp#4]
I still got error:

 Module: 6D
 Start_Address: 1
 ZDC Name: V03935263DB
 ZDC version: 0001
 Login: 20103
Traceback (most recent call last):
  File "C:\Users\pcian\Desktop\odis2vcp-master\odis2vcp.py", line 158, in <module>
    parse_small_oe_file()
  File "C:\Users\pcian\Desktop\odis2vcp-master\odis2vcp.py", line 146, in parse_small_oe_file
    dataset = parameter_data.childNodes[0].data
IndexError: list index out of range

**Comment by Kasparas666** [comment]
I also have problem

C:\Python>python odis2vcp.py -i KD7.xml -d "VW ID4 D7 matrix"
 Module: D7
 Start_Address: 7100
 ZDC Name: V03935389SG
 ZDC version: 0001
 Login: 20103
Traceback (most recent call last):
  File "C:\Python\odis2vcp.py", line 157, in <module>
    parse_small_oe_file()
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\odis2vcp.py", line 145, in parse_small_oe_file
    dataset = parameter_data.childNodes[0].data
              ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Slavixs** [comment]
Same problem.

C:\Users\salvi>python odis2vcp.py -i VW3260EUK0BA.xml -d "2q0_dataset_vcp"
 Module: 3C
 Start_Address: 7100
 ZDC Name: V03935308HF
 ZDC version: 0001
 Login: 20103
Traceback (most recent call last):
  File "C:\Users\salvi\odis2vcp.py", line 157, in <module>
    parse_small_oe_file()
  File "C:\Users\salvi\odis2vcp.py", line 145, in parse_small_oe_file
    dataset = parameter_data.childNodes[0].data
IndexError: list index out of range
